-- This script updates the admin user password to use a Node.js bcryptjs-compatible hash
-- The issue: PostgreSQL's crypt() function creates hashes incompatible with Node.js bcryptjs
-- Solution: Use a hash generated by bcryptjs
-- Password: Admin123!

-- Delete the old admin and insert a new one with a proper bcryptjs hash
DELETE FROM admin_users WHERE email = 'admin@test.com';

INSERT INTO admin_users (email, password_hash)
VALUES (
  'admin@test.com',
  '$2b$10$qIUoKy21uQAi2rllgX9bxecGohHiKmZW46Wwd/vOAbw4M/ROJSxP.'
);

-- Verify the insert
SELECT id, email, created_at FROM admin_users WHERE email = 'admin@test.com';
