-- This script updates the admin user password to use a Node.js bcryptjs-compatible hash
-- The issue: PostgreSQL's crypt() function creates hashes incompatible with Node.js bcryptjs
-- Solution: Use a hash generated by bcryptjs
-- Password: Admin123!

-- Delete the old admin and insert a new one with a proper bcryptjs hash
DELETE FROM admin_users WHERE email = 'admin@test.com';

INSERT INTO admin_users (email, password_hash)
VALUES (
  'admin@test.com',
  '$2a$10$rZ7qJ5k1pG6vXKZHJ5xZxuF7YKGqXPZH0U5mXMf5jFQU8k7N8K5gK'
);

-- Verify the insert
SELECT id, email, created_at FROM admin_users WHERE email = 'admin@test.com';
